%YAML:1.0 # need to specify the file type at the top!

cam0:
  T_cam_imu:
    - [-0.9990674261177589, 0.003631371785536113, 0.04302430951674526, 0.029775744033325717]
    - [-0.0028069257561474303, -0.9998115832434417, 0.019207268937644115, -3.945506719509616e-05]
    - [0.043085951750390296, 0.019068590697760665, 0.9988893780647411, -0.05058322878791149]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: []
  camera_model: pinhole
  distortion_coeffs: [-0.36599825863847607, 0.15566628749131536, 0.003684464282510181,  0.004564651739351755]
  distortion_model: radtan
  intrinsics: [758.1291471478728, 759.5125594392973, 289.0985666049996, 228.23374237672056]
  resolution: [640, 480]
  rostopic: /camera_spinnaker/image_frame
  timeshift_cam_imu: -0.005475324106170151
# cam1:
#   T_cam_imu:
#     - [-0.011823057800830705, -0.9998701444077991, -0.010950325390841398, -0.057904961033265645]
#     - [0.011552991631909482, 0.01081376681432078, -0.9998747875767439, 0.00043766687615362694]
#     - [0.9998633625093938, -0.011948086424720228, 0.011423639621249038, -0.00039944945687402214]
#     - [0.0, 0.0, 0.0, 1.0]
#   T_cn_cnm1:
#     - [0.9998053017199788, 0.011197738450911484, 0.01624713224548414, -0.07961594300469246]
#     - [-0.011147758116324, 0.9999328574031386, -0.0031635699090552883, 0.0007443452072558462]
#     - [-0.016281466199246444, 0.00298183486707869, 0.9998630018753686, 0.0004425529195268342]
#     - [0.0, 0.0, 0.0, 1.0]
#   cam_overlaps: [0]
#   camera_model: pinhole
#   distortion_coeffs: [-0.008456929295619607, 0.011407590938612062, -0.006951788325762078,
#                       0.0015368127092821786]
#   distortion_model: equidistant
#   intrinsics: [277.61640629770613, 277.63749695723294, 314.8944703346039, 236.04310050462587]
#   resolution: [640, 480]
#   rostopic: /snappy_cam/stereo_r
#   timeshift_cam_imu: -0.016591431247074982