%YAML:1.0 # need to specify the file type at the top!

cam0:
  T_cam_imu:
    - [-0.9995991738524179, 0.005137352230635228, 0.027840604261081696, 0.025511174632699758]
    - [-0.005338788412348343, -0.9999600732256928, -0.007165842082780113, 0.00040093104150374986]
    - [0.027802679220750436, -0.007311604921325729, 0.9995866903183648, -0.06778644321079669]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: []
  camera_model: pinhole
  distortion_coeffs: [-0.08095806072593555, 0.15743578875760092, -0.0035154416164982195,  -0.003950567808338846]
  distortion_model: radtan
  intrinsics: [548.8989250692618, 550.0282089284915, 313.5293514832678, 219.6325753720951]
  resolution: [640, 480]
  rostopic: /camera_prophesee/events
  timeshift_cam_imu: 0.0016611976654922291
# cam1:
#   T_cam_imu:
#     - [-0.011823057800830705, -0.9998701444077991, -0.010950325390841398, -0.057904961033265645]
#     - [0.011552991631909482, 0.01081376681432078, -0.9998747875767439, 0.00043766687615362694]
#     - [0.9998633625093938, -0.011948086424720228, 0.011423639621249038, -0.00039944945687402214]
#     - [0.0, 0.0, 0.0, 1.0]
#   T_cn_cnm1:
#     - [0.9998053017199788, 0.011197738450911484, 0.01624713224548414, -0.07961594300469246]
#     - [-0.011147758116324, 0.9999328574031386, -0.0031635699090552883, 0.0007443452072558462]
#     - [-0.016281466199246444, 0.00298183486707869, 0.9998630018753686, 0.0004425529195268342]
#     - [0.0, 0.0, 0.0, 1.0]
#   cam_overlaps: [0]
#   camera_model: pinhole
#   distortion_coeffs: [-0.008456929295619607, 0.011407590938612062, -0.006951788325762078,
#                       0.0015368127092821786]
#   distortion_model: equidistant
#   intrinsics: [277.61640629770613, 277.63749695723294, 314.8944703346039, 236.04310050462587]
#   resolution: [640, 480]
#   rostopic: /snappy_cam/stereo_r
#   timeshift_cam_imu: -0.016591431247074982