%YAML:1.0 # need to specify the file type at the top!

cam0:
  T_cam_imu:
    - [0.9999641031275889, 0.003197881415389814, -0.007846401129833277, 0.001265030971654739]
    - [-0.003216308945288942, 0.9999920967707336, -0.002337039332281246, -0.0025652081547025674]
    - [0.007838865543278494, 0.0023621918900207225, 0.9999664855566258, -0.022231533861925983]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: []
  camera_model: pinhole
  distortion_coeffs: [-0.03252275347038443, 0.0010042799356776398, -0.0048537750326187136, 0.0014604134198771906]
  distortion_model: equidistant
  intrinsics: [173.07989681517137, 173.0734479068749, 163.31033691005516, 134.99889292308214]
  resolution: [346, 260]
  rostopic: /dvs/image_raw
  timeshift_cam_imu: 0.005733889300479769
# cam1:
#   T_cam_imu:
#     - [-0.01749277298389329, -0.9997914625864506, -0.010537278233961556, -0.05569997768397372]
#     - [-0.7090991957246053, 0.019835234209851005, -0.7048296915614142, 0.00884826894411553]
#     - [0.7048917175822481, -0.004857450265962848, -0.7092982952614942, -0.0019997713120269607]
#     - [0.0, 0.0, 0.0, 1.0]
#   T_cn_cnm1:
#     - [0.9998713028057842, 0.0019367839962957476, 0.015925661468614183, -0.07993259169905036]
#     - [-0.0020450612045710957, 0.9999748874354272, 0.0067854420026733295, -7.205400304978925e-05]
#     - [-0.01591211959893364, -0.006817137687752675, 0.9998501543149417, -0.0009141881692325364]
#     - [0.0, 0.0, 0.0, 1.0]
#   cam_overlaps: [0]
#   camera_model: pinhole
#   distortion_coeffs: [-0.012138050918285051, 0.02244029339184358, -0.013753165428754275,
#                       0.002725090438517269]
#   distortion_model: equidistant
#   intrinsics: [274.4628309070672, 273.9261674470783, 315.93654481793794, 235.779167375461]
#   resolution: [640, 480]
#   rostopic: /snappy_cam/stereo_r
#   timeshift_cam_imu: -0.014950736007814259