%YAML:1.0

cam0:
  T_imu_cam: #rotation from camera to IMU R_CtoI, position of camera in IMU p_CinI
    - [0.99995523,  0.00599467, -0.00732165, -0.00054603]
    - [-0.00603191,  0.99996893, -0.00507505, 0.00046837]
    - [0.007291,    0.00511898,  0.99996032, 0.06016175]
    - [0.0, 0.0, 0.0, 1.0]

    # - [0.00729100,0.00511899,0.99996032,-0.06016175]  
    # - [-0.99995523,-0.00599467,0.00732165,0.00054603]
    # - [0.00603191,-0.99996893,0.00507505,-0.00046837]
    # - [0.0, 0.0, 0.0, 1.0]

  cam_overlaps: []
  camera_model: pinhole
  distortion_coeffs: [-0.3674645003666135, 0.13685246896794986, -0.0004006812242899775, 3.0969134907500055e-05]
  distortion_model: radtan
  intrinsics: [249.69341447817564, 248.41625664694038, 176.74240257052816, 129.47631010746218] #fu, fv, cu, cv
  resolution: [346, 260]
  rostopic: /davis_left/image_raw
# cam1:
#   T_imu_cam: #rotation from camera to IMU R_CtoI, position of camera in IMU p_CinI
#     - [0.0125552670891, -0.999755099723, 0.0182237714554, -0.0198435579556]
#     - [0.999598781151, 0.0130119051815, 0.0251588363115, 0.0453689425024]
#     - [-0.0253898008918, 0.0179005838253, 0.999517347078, 0.00786212447038]
#     - [0.0, 0.0, 0.0, 1.0]
#   cam_overlaps: [0]
#   camera_model: pinhole
#   distortion_coeffs: [-0.28368365,0.07451284,-0.00010473,-3.55590700e-05]
#   distortion_model: radtan
#   intrinsics: [457.587, 456.134, 379.999, 255.238] #fu, fv, cu, cv
#   resolution: [752, 480]
#   rostopic: /cam1/image_raw