%YAML:1.0

cam0:
  T_imu_cam: #rotation from camera to IMU R_CtoI, position of camera in IMU p_CinI
    - [0.9999,  -0.0122, 0.0063, 0.0067]
    - [0.0121,0.9998,0.0093,0.0007]
    - [-0.0064,-0.0092,0.9999,0.0342]
    - [0.0, 0.0, 0.0, 1.0]

  cam_overlaps: []
  camera_model: pinhole
  distortion_coeffs: [-0.368436311798, 0.150947243557, -0.000296130534385, -0.000759431726241]
  distortion_model: radtan
  intrinsics: [199.092366542, 198.82882047, 132.192071378, 110.712660011] #fu, fv, cu, cv
  resolution: [240, 180]
  rostopic: /dvs/image_raw
# cam1:
#   T_imu_cam: #rotation from camera to IMU R_CtoI, position of camera in IMU p_CinI
#     - [0.0125552670891, -0.999755099723, 0.0182237714554, -0.0198435579556]
#     - [0.999598781151, 0.0130119051815, 0.0251588363115, 0.0453689425024]
#     - [-0.0253898008918, 0.0179005838253, 0.999517347078, 0.00786212447038]
#     - [0.0, 0.0, 0.0, 1.0]
#   cam_overlaps: [0]
#   camera_model: pinhole
#   distortion_coeffs: [-0.28368365,0.07451284,-0.00010473,-3.55590700e-05]
#   distortion_model: radtan
#   intrinsics: [457.587, 456.134, 379.999, 255.238] #fu, fv, cu, cv
#   resolution: [752, 480]
#   rostopic: /cam1/image_raw