%YAML:1.0 # need to specify the file type at the top!

cam0:
  T_cam_imu:
    - [0.9998829655327196, 0.005335413966337045, -0.014338360969823338, -0.0015224098391112568]
    - [-0.005432624310654592, 0.9999624656424586, -0.006749362884958196, -0.006621897399791399]
    - [0.014301812143655866, 0.00682646790524808, 0.9998744208676132, -0.023154837302635834]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: []
  camera_model: pinhole
  distortion_coeffs: [-0.03560363132286886, 0.001974723646350411, -0.0045671620060236855, 0.0011707729112974909]
  distortion_model: equidistant
  intrinsics: [174.23979032083346, 174.11105443010973, 163.91078563399876, 140.9726709818771]
  resolution: [346, 260]
  rostopic: /dvs/events
  timeshift_cam_imu: 0.005808240975061038
# cam1:
#   T_cam_imu:
#     - [-0.011450159873389598, -0.9998746482793399, -0.010935335712288774, -0.05828448770624624]
#     - [0.009171247533644289, 0.010830579777447058, -0.9998992883087583, -0.0002362068202437068]
#     - [0.999892385238307, -0.01154929737910465, 0.009046086032012068, -0.00947464531803495]
#     - [0.0, 0.0, 0.0, 1.0]
#   T_cn_cnm1:
#     - [0.9997470623689986, 0.009836089265916417, 0.020225296846065624, -0.07919358086270675]
#     - [-0.00975774768296796, 0.9999445171722606, -0.0039684930755682956, 0.000831414953842084]
#     - [-0.020263209141547188, 0.0037701359508940783, 0.9997875716521978, 0.00044568632114983057]
#     - [0.0, 0.0, 0.0, 1.0]
#   cam_overlaps: [0]
#   camera_model: pinhole
#   distortion_coeffs: [-0.009025009906076716, 0.009967427035376123, -0.0029538969814842117,
#                       -0.0003503551771748748]
#   distortion_model: equidistant
#   intrinsics: [276.78679780974477, 276.79332134030807, 314.2862327340746, 236.51313088043128]
#   resolution: [640, 480]
#   rostopic: /snappy_cam/stereo_r
#   timeshift_cam_imu: -0.007983859928063504