%YAML:1.0 # need to specify the file type at the top!

cam0:
  T_cam_imu:
    - [0.9999641031275889, 0.003197881415389814, -0.007846401129833277, 0.001265030971654739]
    - [-0.003216308945288942, 0.9999920967707336, -0.002337039332281246, -0.0025652081547025674]
    - [0.007838865543278494, 0.0023621918900207225, 0.9999664855566258, -0.022231533861925983]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: []
  camera_model: pinhole
  distortion_coeffs: [-0.027576733308582076, -0.006593578674675004, 0.0008566938165177085, -0.00030899587045247486]
  distortion_model: equidistant
  intrinsics: [172.98992850734132, 172.98303181090185, 163.33639726024606, 134.99537889030861]
  resolution: [346, 260]
  rostopic: /dvs/image_raw
  timeshift_cam_imu: 0.005532805640108713
# cam1:
#   T_cam_imu:
#     - [-0.011823057800830705, -0.9998701444077991, -0.010950325390841398, -0.057904961033265645]
#     - [0.011552991631909482, 0.01081376681432078, -0.9998747875767439, 0.00043766687615362694]
#     - [0.9998633625093938, -0.011948086424720228, 0.011423639621249038, -0.00039944945687402214]
#     - [0.0, 0.0, 0.0, 1.0]
#   T_cn_cnm1:
#     - [0.9998053017199788, 0.011197738450911484, 0.01624713224548414, -0.07961594300469246]
#     - [-0.011147758116324, 0.9999328574031386, -0.0031635699090552883, 0.0007443452072558462]
#     - [-0.016281466199246444, 0.00298183486707869, 0.9998630018753686, 0.0004425529195268342]
#     - [0.0, 0.0, 0.0, 1.0]
#   cam_overlaps: [0]
#   camera_model: pinhole
#   distortion_coeffs: [-0.008456929295619607, 0.011407590938612062, -0.006951788325762078,
#                       0.0015368127092821786]
#   distortion_model: equidistant
#   intrinsics: [277.61640629770613, 277.63749695723294, 314.8944703346039, 236.04310050462587]
#   resolution: [640, 480]
#   rostopic: /snappy_cam/stereo_r
#   timeshift_cam_imu: -0.016591431247074982